//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.07 at 01:40:17 PM CET 
//


package it.unipr.ce.dsg.deus.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="logger" type="{http://dsg.ce.unipr.it/software/deus/schema/automator}logger" minOccurs="0"/>
 *         &lt;element name="params" type="{http://dsg.ce.unipr.it/software/deus/schema/automator}params" minOccurs="0"/>
 *         &lt;element name="events" type="{http://dsg.ce.unipr.it/software/deus/schema/automator}references" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="handler" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schedulerListener" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="oneShot" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="distributionLevel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "event", propOrder = {
    "logger",
    "params",
    "events"
})
public class Event {

    protected Logger logger;
    protected Params params;
    protected References events;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    protected String handler;
    @XmlAttribute
    protected String schedulerListener;
    @XmlAttribute
    protected Boolean oneShot;
    @XmlAttribute
    protected String distributionLevel;

    /**
     * Gets the value of the logger property.
     * 
     * @return
     *     possible object is
     *     {@link Logger }
     *     
     */
    public Logger getLogger() {
        return logger;
    }

    /**
     * Sets the value of the logger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logger }
     *     
     */
    public void setLogger(Logger value) {
        this.logger = value;
    }

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link Params }
     *     
     */
    public Params getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link Params }
     *     
     */
    public void setParams(Params value) {
        this.params = value;
    }

    /**
     * Gets the value of the events property.
     * 
     * @return
     *     possible object is
     *     {@link References }
     *     
     */
    public References getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *     allowed object is
     *     {@link References }
     *     
     */
    public void setEvents(References value) {
        this.events = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the handler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandler() {
        return handler;
    }

    /**
     * Sets the value of the handler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandler(String value) {
        this.handler = value;
    }

    /**
     * Gets the value of the schedulerListener property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulerListener() {
        return schedulerListener;
    }

    /**
     * Sets the value of the schedulerListener property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulerListener(String value) {
        this.schedulerListener = value;
    }

    /**
     * Gets the value of the oneShot property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOneShot() {
        return oneShot;
    }

    /**
     * Sets the value of the oneShot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOneShot(Boolean value) {
        this.oneShot = value;
    }

    /**
     * Gets the value of the distributionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistributionLevel() {
        return distributionLevel;
    }

    /**
     * Sets the value of the distributionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistributionLevel(String value) {
        this.distributionLevel = value;
    }

}
