//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.08 at 05:19:25 PM CET 
//


package it.unipr.ce.dsg.deus.schema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simulation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simulation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="node" type="{http://dsg.ce.unipr.it/software/deus/schema/deusAutomator}node" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="process" type="{http://dsg.ce.unipr.it/software/deus/schema/deusAutomator}process" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="engine" type="{http://dsg.ce.unipr.it/software/deus/schema/deusAutomator}engine" minOccurs="0"/>
 *         &lt;element name="resultVT" type="{http://dsg.ce.unipr.it/software/deus/schema/deusAutomator}resultVT" minOccurs="0"/>
 *         &lt;element name="resultXYFile" type="{http://dsg.ce.unipr.it/software/deus/schema/deusAutomator}resultXYFile" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="simulationNumberSeed" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="simulationName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resultFolder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inputFolder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simulation", propOrder = {
    "node",
    "process",
    "engine",
    "resultVT",
    "resultXYFile"
})
public class Simulation {

    protected List<Node> node;
    protected List<Process> process;
    protected Engine engine;
    protected ResultVT resultVT;
    protected List<ResultXYFile> resultXYFile;
    @XmlAttribute(required = true)
    protected BigInteger simulationNumberSeed;
    @XmlAttribute(required = true)
    protected String simulationName;
    @XmlAttribute
    protected String resultFolder;
    @XmlAttribute
    protected String inputFolder;

    /**
     * Gets the value of the node property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the node property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Node }
     * 
     * 
     */
    public List<Node> getNode() {
        if (node == null) {
            node = new ArrayList<Node>();
        }
        return this.node;
    }

    /**
     * Gets the value of the process property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the process property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Process }
     * 
     * 
     */
    public List<Process> getProcess() {
        if (process == null) {
            process = new ArrayList<Process>();
        }
        return this.process;
    }

    /**
     * Gets the value of the engine property.
     * 
     * @return
     *     possible object is
     *     {@link Engine }
     *     
     */
    public Engine getEngine() {
        return engine;
    }

    /**
     * Sets the value of the engine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Engine }
     *     
     */
    public void setEngine(Engine value) {
        this.engine = value;
    }

    /**
     * Gets the value of the resultVT property.
     * 
     * @return
     *     possible object is
     *     {@link ResultVT }
     *     
     */
    public ResultVT getResultVT() {
        return resultVT;
    }

    /**
     * Sets the value of the resultVT property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultVT }
     *     
     */
    public void setResultVT(ResultVT value) {
        this.resultVT = value;
    }

    /**
     * Gets the value of the resultXYFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultXYFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultXYFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultXYFile }
     * 
     * 
     */
    public List<ResultXYFile> getResultXYFile() {
        if (resultXYFile == null) {
            resultXYFile = new ArrayList<ResultXYFile>();
        }
        return this.resultXYFile;
    }

    /**
     * Gets the value of the simulationNumberSeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSimulationNumberSeed() {
        return simulationNumberSeed;
    }

    /**
     * Sets the value of the simulationNumberSeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSimulationNumberSeed(BigInteger value) {
        this.simulationNumberSeed = value;
    }

    /**
     * Gets the value of the simulationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimulationName() {
        return simulationName;
    }

    /**
     * Sets the value of the simulationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimulationName(String value) {
        this.simulationName = value;
    }

    /**
     * Gets the value of the resultFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultFolder() {
        return resultFolder;
    }

    /**
     * Sets the value of the resultFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultFolder(String value) {
        this.resultFolder = value;
    }

    /**
     * Gets the value of the inputFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputFolder() {
        return inputFolder;
    }

    /**
     * Sets the value of the inputFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputFolder(String value) {
        this.inputFolder = value;
    }

}
