//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.07 at 01:41:15 PM CET 
//


package it.unipr.ce.dsg.deus.schema.automator;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.unipr.ce.dsg.deus.schema.automator package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeusAutomator_QNAME = new QName("http://dsg.ce.unipr.it/software/deus/schema/deusAutomator", "deusAutomator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.unipr.ce.dsg.deus.schema.automator
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeusAutomator }
     * 
     */
    public DeusAutomator createDeusAutomator() {
        return new DeusAutomator();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Seed }
     * 
     */
    public Seed createSeed() {
        return new Seed();
    }

    /**
     * Create an instance of {@link ResultVT }
     * 
     */
    public ResultVT createResultVT() {
        return new ResultVT();
    }

    /**
     * Create an instance of {@link Simulation }
     * 
     */
    public Simulation createSimulation() {
        return new Simulation();
    }

    /**
     * Create an instance of {@link ParamName }
     * 
     */
    public ParamName createParamName() {
        return new ParamName();
    }

    /**
     * Create an instance of {@link ResultXYFile }
     * 
     */
    public ResultXYFile createResultXYFile() {
        return new ResultXYFile();
    }

    /**
     * Create an instance of {@link Engine }
     * 
     */
    public Engine createEngine() {
        return new Engine();
    }

    /**
     * Create an instance of {@link ResourceParamName }
     * 
     */
    public ResourceParamName createResourceParamName() {
        return new ResourceParamName();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeusAutomator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dsg.ce.unipr.it/software/deus/schema/deusAutomator", name = "deusAutomator")
    public JAXBElement<DeusAutomator> createDeusAutomator(DeusAutomator value) {
        return new JAXBElement<DeusAutomator>(_DeusAutomator_QNAME, DeusAutomator.class, null, value);
    }

}
