//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.07 at 01:41:15 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dsg.ce.unipr.it/software/deus/schema/deusAutomator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.unipr.ce.dsg.deus.schema.automator;
